name: Publish

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Latest Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.1.0
      with:
        python-version: 3.8
        architecture: x64

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        pip --version

    - name: Install Poetry
      run: |
        python -m pip install poetry
        poetry --version

    - name: Install Dependencies
      run: |
        make init

    - name: Configure PYPI Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Publish Package
      run: poetry publish --build
